/*
CREATED: 12/11/2017
MODIFIED: 04/12/2017
MODEL: ALI-ALL_IN_ONE
DATABASE: POSTGRESQL 9.4
*/


-- DROP INDEXES SECTION -------------------------------------------------

DROP INDEX IF EXISTS IDX_REL_ALLESTIMENTI_MATERIALI
;


-- DROP TABLES SECTION ---------------------------------------------------

DROP TABLE IF EXISTS MATERIALI CASCADE
;
DROP TABLE IF EXISTS ALLESTIMENTI CASCADE
;
DROP TABLE IF EXISTS SPECIFICHE_ALLESTIMENTO CASCADE
;
DROP TABLE IF EXISTS PRODOTTI_GAS CASCADE
;
DROP TABLE IF EXISTS IMPUREZZE_GARANTITE CASCADE
;
DROP TABLE IF EXISTS PRODOTTI_GAS_COMP CASCADE
;
DROP TABLE IF EXISTS FAMIGLIA_PRODOTTI_GAS CASCADE
;

-- CREATE TABLES SECTION -------------------------------------------------

-- TABLE FAMIGLIA_PRODOTTI_GAS

CREATE TABLE FAMIGLIA_PRODOTTI_GAS(
 ID_FAMIGLIA SERIAL NOT NULL,
 CODICE_FAMIGLIA CHARACTER VARYING(30) NOT NULL,
 NOME_COMMERCIALE CHARACTER VARYING(30) NOT NULL,
 FL_PUBBLICATO BOOLEAN DEFAULT FALSE NOT NULL,
 FL_OBSOLETO BOOLEAN DEFAULT FALSE NOT NULL,
 PRESSIONE_CARICA CHARACTER VARYING(20),
 SCHEDA_SICUREZZA CHARACTER VARYING(50),
 SITI_ABILITATI CHARACTER VARYING,
 COLORE_CORPO CHARACTER VARYING(50),
 COLORE_OGIVA CHARACTER VARYING(50),
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- ADD KEYS FOR TABLE FAMIGLIA_PRODOTTI_GAS

ALTER TABLE FAMIGLIA_PRODOTTI_GAS ADD CONSTRAINT PK_FAMIGLIA PRIMARY KEY (ID_FAMIGLIA)
;

-- TABLE PRODOTTI_GAS_COMP

CREATE TABLE PRODOTTI_GAS_COMP(
 ID_PRODOTTI_GAS_COMP SERIAL NOT NULL,
 ID_FAMIGLIA INTEGER NOT NULL,
 CODICE_COMPONENTE CHARACTER(3) NOT NULL,
 COMPOSIZIONE_PERC CHARACTER VARYING(20) NOT NULL,
 CODICE_STRUMENTO_ANALISI CHARACTER(3),
 CODICE_FREQUENZA_ANALISI CHARACTER(3),
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- ADD KEYS FOR TABLE PRODOTTI_GAS_COMP

ALTER TABLE PRODOTTI_GAS_COMP ADD CONSTRAINT FK_PRODOTTI_GAS_COMP PRIMARY KEY (ID_PRODOTTI_GAS_COMP,ID_FAMIGLIA)
;

ALTER TABLE PRODOTTI_GAS_COMP ADD CONSTRAINT PK_PRODOTTI_GAS_COMP UNIQUE (ID_PRODOTTI_GAS_COMP)
;

-- TABLE IMPUREZZE_GARANTITE

CREATE TABLE IMPUREZZE_GARANTITE(
 ID_IMPUREZZE_GARANTITE SERIAL NOT NULL,
 ID_FAMIGLIA INTEGER NOT NULL,
 CODICE_IMPUREZZA CHARACTER(3) NOT NULL,
 SOGLIA_ANALISI CHARACTER VARYING(20),
 DA_PROCESSO CHARACTER VARYING(20),
 CODICE_STRUMENTO_ANALISI CHARACTER(3),
 CODICE_FREQUENZA_ANALISI CHARACTER(3),
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- ADD KEYS FOR TABLE IMPUREZZE_GARANTITE

ALTER TABLE IMPUREZZE_GARANTITE ADD CONSTRAINT FK_IMPUREZZE_GARANTITE PRIMARY KEY (ID_IMPUREZZE_GARANTITE,ID_FAMIGLIA)
;

ALTER TABLE IMPUREZZE_GARANTITE ADD CONSTRAINT PK_IMPUREZZE_GARANTITE UNIQUE (ID_IMPUREZZE_GARANTITE)
;

-- TABLE PRODOTTI_GAS

CREATE TABLE PRODOTTI_GAS(
 ID_PRODOTTI_GAS SERIAL NOT NULL,
 ID_FAMIGLIA INTEGER NOT NULL,
 CODICE_FAMIGLIA_ALLESTIMENTO CHARACTER(3) NOT NULL,
 CODICE_PRODOTTO CHARACTER VARYING(30) NOT NULL,
 DESCRIZIONE_PRODOTTO CHARACTER VARYING(50) NOT NULL,
 CODICE_ALLESTIMENTO CHARACTER(3) NOT NULL,
 CODICE_ETICHETTA_ADR CHARACTER(3) NOT NULL,
 CODICE_SAP_ETICHETTA CHARACTER VARYING(20) NOT NULL,
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- ADD KEYS FOR TABLE PRODOTTI_GAS

ALTER TABLE PRODOTTI_GAS ADD CONSTRAINT FK_PRODOTTI_GAS PRIMARY KEY (ID_PRODOTTI_GAS,ID_FAMIGLIA)
;

ALTER TABLE PRODOTTI_GAS ADD CONSTRAINT PK_PRODOTTI_GAS UNIQUE (ID_PRODOTTI_GAS)
;

-- TABLE SPECIFICHE_ALLESTIMENTO

CREATE TABLE SPECIFICHE_ALLESTIMENTO(
 ID_SPECIFICA SERIAL NOT NULL,
 ID_FAMIGLIA INTEGER NOT NULL,
 ID_ALLESTIMENTO INTEGER NOT NULL,
 DESCRIZIONE CHARACTER VARYING(50) NOT NULL,
 ID_MATERIALE INTEGER,
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- CREATE INDEXES FOR TABLE SPECIFICHE_ALLESTIMENTO

CREATE INDEX IDX_REL_ALLESTIMENTI_MATERIALI ON SPECIFICHE_ALLESTIMENTO (ID_MATERIALE)
;

-- ADD KEYS FOR TABLE SPECIFICHE_ALLESTIMENTO

ALTER TABLE SPECIFICHE_ALLESTIMENTO ADD CONSTRAINT FK_SPECIFICHE_ALLESTIMENTO PRIMARY KEY (ID_SPECIFICA,ID_FAMIGLIA,ID_ALLESTIMENTO)
;

ALTER TABLE SPECIFICHE_ALLESTIMENTO ADD CONSTRAINT PK_SPECIFICHE_ALLESTIMENTO UNIQUE (ID_SPECIFICA)
;

-- TABLE ALLESTIMENTI

CREATE TABLE ALLESTIMENTI(
 ID_ALLESTIMENTO SERIAL NOT NULL,
 CODICE_ALLESTIMENTO CHARACTER(3) NOT NULL,
 ORDINE INTEGER NOT NULL,
 CARATTERISTICA CHARACTER VARYING(50) NOT NULL,
 FL_MATERIALE BOOLEAN DEFAULT FALSE NOT NULL,
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- ADD KEYS FOR TABLE ALLESTIMENTI

ALTER TABLE ALLESTIMENTI ADD CONSTRAINT PK_ALLESTIMENTI PRIMARY KEY (ID_ALLESTIMENTO)
;

ALTER TABLE ALLESTIMENTI ADD CONSTRAINT K1_ALLESTIMENTI UNIQUE (ID_ALLESTIMENTO)
;

-- TABLE MATERIALI

CREATE TABLE MATERIALI(
 ID_MATERIALE SERIAL NOT NULL,
 DESCRIZIONE CHARACTER VARYING(50) NOT NULL,
 CODICE_SAP CHARACTER VARYING(20)
)
;

-- ADD KEYS FOR TABLE MATERIALI

ALTER TABLE MATERIALI ADD CONSTRAINT PK_MATERIALE PRIMARY KEY (ID_MATERIALE)
;

ALTER TABLE MATERIALI ADD CONSTRAINT K1_MATERIALE UNIQUE (ID_MATERIALE)
;
-- CREATE FOREIGN KEYS (RELATIONSHIPS) SECTION ------------------------------------------------- 

ALTER TABLE PRODOTTI_GAS_COMP ADD CONSTRAINT REL_FK_PRODOTTI_GAS_COMP FOREIGN KEY (ID_FAMIGLIA) REFERENCES FAMIGLIA_PRODOTTI_GAS (ID_FAMIGLIA) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE IMPUREZZE_GARANTITE ADD CONSTRAINT REL_FK_IMPUREZZE_GARANTITE FOREIGN KEY (ID_FAMIGLIA) REFERENCES FAMIGLIA_PRODOTTI_GAS (ID_FAMIGLIA) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE PRODOTTI_GAS ADD CONSTRAINT REL_FK_PRODOTTI_GAS FOREIGN KEY (ID_FAMIGLIA) REFERENCES FAMIGLIA_PRODOTTI_GAS (ID_FAMIGLIA) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE SPECIFICHE_ALLESTIMENTO ADD CONSTRAINT REL_FK_ALLESTIMENTI FOREIGN KEY (ID_FAMIGLIA) REFERENCES FAMIGLIA_PRODOTTI_GAS (ID_FAMIGLIA) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE SPECIFICHE_ALLESTIMENTO ADD CONSTRAINT REL_FK_SPECIFICHE_ALLESTIMENTI FOREIGN KEY (ID_ALLESTIMENTO) REFERENCES ALLESTIMENTI (ID_ALLESTIMENTO) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE SPECIFICHE_ALLESTIMENTO ADD CONSTRAINT REL_ALLESTIMENTI_MATERIALI FOREIGN KEY (ID_MATERIALE) REFERENCES MATERIALI (ID_MATERIALE) ON DELETE NO ACTION ON UPDATE NO ACTION
;




