update AREA_LAVORO set RECT_X_STAMPA =36  WHERE ID_AREA=938;
update AREA_LAVORO set RECT_Y_STAMPA =645  WHERE ID_AREA=938;
update AREA_LAVORO set RECT_W_STAMPA =141  WHERE ID_AREA=938;
update AREA_LAVORO set RECT_H_STAMPA =75  WHERE ID_AREA=938;

update AREA_LAVORO set RECT_X_STAMPA =386 WHERE ID_AREA=943;
update AREA_LAVORO set RECT_Y_STAMPA =647 WHERE ID_AREA=943;
update AREA_LAVORO set RECT_W_STAMPA =130 WHERE ID_AREA=943;
update AREA_LAVORO set RECT_H_STAMPA =70 WHERE ID_AREA=943;


update AREA_LAVORO set RECT_X_STAMPA =670 WHERE ID_AREA=902;
update AREA_LAVORO set RECT_Y_STAMPA =647 WHERE ID_AREA=902;
update AREA_LAVORO set RECT_W_STAMPA =130 WHERE ID_AREA=902;
update AREA_LAVORO set RECT_H_STAMPA =70 WHERE ID_AREA=902 ;	


update AREA_LAVORO set RECT_X_STAMPA =1008 WHERE ID_AREA=927;
update AREA_LAVORO set RECT_Y_STAMPA =645 WHERE ID_AREA=927;
update AREA_LAVORO set RECT_W_STAMPA =140 WHERE ID_AREA=927;
update AREA_LAVORO set RECT_H_STAMPA =70 WHERE ID_AREA=927 	;
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =35 WHERE ID_AREA=940;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=940;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=940;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=940 ;	


update AREA_LAVORO set RECT_X_STAMPA =160 WHERE ID_AREA=964;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=964;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=964;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=964 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =285 WHERE ID_AREA=954;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=954;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=954;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=954 ;	


update AREA_LAVORO set RECT_X_STAMPA =410 WHERE ID_AREA=948;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=948;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=948;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=948 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =535 WHERE ID_AREA=933;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=933;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=933;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=933 ;	


update AREA_LAVORO set RECT_X_STAMPA =660 WHERE ID_AREA=911;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=911;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=911;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=911 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =783 WHERE ID_AREA=928;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=928;
update AREA_LAVORO set RECT_W_STAMPA =117 WHERE ID_AREA=928;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=928 ;	


update AREA_LAVORO set RECT_X_STAMPA =910 WHERE ID_AREA=962 ;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=962 ;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=962 ;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=962  ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =1034 WHERE ID_AREA=967  ;
update AREA_LAVORO set RECT_Y_STAMPA =562 WHERE ID_AREA=967   ;
update AREA_LAVORO set RECT_W_STAMPA =117 WHERE ID_AREA=967   ;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=967 ;	



update AREA_LAVORO set RECT_X_STAMPA =35 WHERE ID_AREA=926  ;
update AREA_LAVORO set RECT_Y_STAMPA =478 WHERE ID_AREA=926 ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=926 ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=926 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =767 WHERE ID_AREA=968  ;
update AREA_LAVORO set RECT_Y_STAMPA =440 WHERE ID_AREA=968  ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=968  ;
update AREA_LAVORO set RECT_H_STAMPA =60 WHERE ID_AREA=968	;	


update AREA_LAVORO set RECT_X_STAMPA =1034 WHERE ID_AREA=924  ;
update AREA_LAVORO set RECT_Y_STAMPA =478 WHERE ID_AREA=924   ;
update AREA_LAVORO set RECT_W_STAMPA =117 WHERE ID_AREA=924   ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=924 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =35 WHERE ID_AREA=914    ;
update AREA_LAVORO set RECT_Y_STAMPA =395 WHERE ID_AREA=914   ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=914   ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=914 ;	


update AREA_LAVORO set RECT_X_STAMPA =1034 WHERE ID_AREA=901  ;
update AREA_LAVORO set RECT_Y_STAMPA =395 WHERE ID_AREA=901   ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=901   ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=901 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =35 WHERE ID_AREA=939   ;
update AREA_LAVORO set RECT_Y_STAMPA =315 WHERE ID_AREA=939  ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=939  ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=939 ;	


update AREA_LAVORO set RECT_X_STAMPA =890 WHERE ID_AREA=955  ;
update AREA_LAVORO set RECT_Y_STAMPA =330 WHERE ID_AREA=955  ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=955  ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=955 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =1034 WHERE ID_AREA=942  ;
update AREA_LAVORO set RECT_Y_STAMPA =315 WHERE ID_AREA=942   ;
update AREA_LAVORO set RECT_W_STAMPA =117 WHERE ID_AREA=942   ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=942 ;	


update AREA_LAVORO set RECT_X_STAMPA =35 WHERE ID_AREA=950    ;
update AREA_LAVORO set RECT_Y_STAMPA =230 WHERE ID_AREA=950   ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=950   ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=950 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =1034 WHERE ID_AREA=958   ;
update AREA_LAVORO set RECT_Y_STAMPA =230 WHERE ID_AREA=958    ;
update AREA_LAVORO set RECT_W_STAMPA =117 WHERE ID_AREA=958    ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=958 	;


update AREA_LAVORO set RECT_X_STAMPA =35 WHERE ID_AREA=923      ;
update AREA_LAVORO set RECT_Y_STAMPA =150 WHERE ID_AREA=923     ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=923     ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=923 	 ;
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =285 WHERE ID_AREA=917     ;
update AREA_LAVORO set RECT_Y_STAMPA =155 WHERE ID_AREA=917     ;
update AREA_LAVORO set RECT_W_STAMPA =117 WHERE ID_AREA=917     ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=917 	 ;


update AREA_LAVORO set RECT_X_STAMPA =1034 WHERE ID_AREA=951    ;
update AREA_LAVORO set RECT_Y_STAMPA =150 WHERE ID_AREA=951     ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=951     ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=951 	 ;



update AREA_LAVORO set RECT_X_STAMPA =35 WHERE ID_AREA=945      ;
update AREA_LAVORO set RECT_Y_STAMPA =65 WHERE ID_AREA=945      ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=945     ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=945 	 ;
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =160 WHERE ID_AREA=944    ;
update AREA_LAVORO set RECT_Y_STAMPA =65 WHERE ID_AREA=944     ;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=944    ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=944 	;


update AREA_LAVORO set RECT_X_STAMPA =285 WHERE ID_AREA=913 ;
update AREA_LAVORO set RECT_Y_STAMPA =65 WHERE ID_AREA=913  ;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=913 ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=913 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =410  WHERE ID_AREA=953  ;
update AREA_LAVORO set RECT_Y_STAMPA =65 WHERE ID_AREA=953    ;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=953   ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=953 ;	


update AREA_LAVORO set RECT_X_STAMPA =535 WHERE ID_AREA=947    ;
update AREA_LAVORO set RECT_Y_STAMPA =65 WHERE ID_AREA=947     ;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=947    ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=947 	;
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =660 WHERE ID_AREA=937  ;
update AREA_LAVORO set RECT_Y_STAMPA =65 WHERE ID_AREA=937   ;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=937  ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=937 ;	


update AREA_LAVORO set RECT_X_STAMPA =783 WHERE ID_AREA=961   ;
update AREA_LAVORO set RECT_Y_STAMPA =65 WHERE ID_AREA=961    ;
update AREA_LAVORO set RECT_W_STAMPA =116 WHERE ID_AREA=961   ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=961 ;	
                             
                             
update AREA_LAVORO set RECT_X_STAMPA =910 WHERE ID_AREA=916  ;
update AREA_LAVORO set RECT_Y_STAMPA =65 WHERE ID_AREA=916   ;
update AREA_LAVORO set RECT_W_STAMPA =115 WHERE ID_AREA=916  ;
update AREA_LAVORO set RECT_H_STAMPA =62 WHERE ID_AREA=916 ;	

update AREA_LAVORO set A_CAPO_STAMPA=10