DROP VIEW IF exists V_CHECKLIST;



ALTER TABLE checklist_agenzie ALTER COLUMN portata_carrello TYPE numeric(10,2),
ALTER TABLE checklist_agenzie ALTER COLUMN portata_trans_elettr TYPE numeric(10,2),
ALTER TABLE checklist_agenzie ALTER COLUMN portata_trans_manual TYPE numeric(10,2),
 


CREATE VIEW V_CHECKLIST
AS
SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		--,CON.NOME_COGNOME DESCR_CON
		,MOD.REFERENTE AS DESCR_CON
	FROM checklist_agenzie AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;