ALTER TABLE PDL ADD column MOTIVO_SCADENZA character varying(255);

ALTER TABLE PDL ADD column ID_UTENTE_VERIFICA integer;
ALTER TABLE PDL ADD column TS_VERIFICA timestamp;
ALTER TABLE PDL ADD column RISPOSTA_VERIFICA char(1);