
-- TABLE DIPENDENZE_PDL

CREATE TABLE DIPENDENZE_PDL(
 ID_DIPENDENZE_PDL SERIAL NOT NULL,
 ID_PDL INTEGER NOT NULL,
 ID_DIPENDENZA INTEGER NOT NULL
)
;

-- CREATE INDEXES FOR TABLE DIPENDENZE_PDL

CREATE INDEX IDX_DIPENDENZE_PDL_FK ON DIPENDENZE_PDL (ID_DIPENDENZA,ID_PDL)
;