
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS DESCRIZIONE_EVENTO CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN DESCRIZIONE_EVENTO TEXT;
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS DESCRIZIONE_AZIONI CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN DESCRIZIONE_AZIONI TEXT;

ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_TIPO_IMPIANTO CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_TIPO_IMPIANTO CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_NATURA_EVENTO CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_NATURA_EVENTO CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_PRODOTTO_PERTINENTE CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_PRODOTTO_PERTINENTE CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_GIORNI CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_GIORNI CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_ORE CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_ORE CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_MIN CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_MIN CHAR(3);


ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_MIN CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_MIN CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_CODICE_CATEGORIA_PERSONALE CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_CODICE_CATEGORIA_PERSONALE CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_CODICE_TIPO_INFORTUNIO CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_CODICE_TIPO_INFORTUNIO CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_CODICE_ATTREZZATURA_INTERESSATA CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_CODICE_ATTREZZATURA_INTERESSATA CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_COMP_ATTR_INTERESSATA CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_COMP_ATTR_INTERESSATA CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_GG_PROGNOSI CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_GG_PROGNOSI CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_LESIONE_MAGGIORE CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_LESIONE_MAGGIORE CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_PARTE_CORPO CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_PARTE_CORPO CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_ALTRE_LESIONI CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_ALTRE_LESIONI CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_ALTRE_LESIONI_PARTE_CORPO CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_ALTRE_LESIONI_PARTE_CORPO CHAR(3);


ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_AFF_ATTREZZATURA_INTERESSATA CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_AFF_ATTREZZATURA_INTERESSATA CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_AFF_COMP_ATTR_INTERESSATA CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_AFF_COMP_ATTR_INTERESSATA CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_COSTI_EURO CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_COSTI_EURO CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_LIVELLO_INCIDENTE CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_LIVELLO_INCIDENTE CHAR(3);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS CODICE_CLIENTE CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN CODICE_CLIENTE CHAR(3);

ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS RECLAMO_CLIENTE CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN RECLAMO_CLIENTE CHAR(1);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS FORZA_MAGGIORE CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN FORZA_MAGGIORE CHAR(1);
ALTER TABLE ALIMOD80 DROP COLUMN IF EXISTS ALTRI_CLIENTI CASCADE; ALTER TABLE ALIMOD80 ADD COLUMN ALTRI_CLIENTI VARCHAR;


