ALTER TABLE PDL ADD column NOME_COGNOME_PREPOSTO_IMPRESA_2 character varying;
ALTER TABLE PDL ADD column NOME_COGNOME_DELEGATO_LAVORI_AL_2 character varying;


ALTER TABLE PDL ADD column ID_UTENTE_PRIMA_ATTIVAZIONE integer;