update impianti set fl_disattivo=true where id_azienda=39;
update area_lavoro set fl_disattivo=true where id_impianto in (select id_impianto from impianti where id_azienda=39);
update equipment set fl_disattivo=true where id_area in (select id_area from area_lavoro where id_impianto in (select id_impianto from impianti where id_azienda=39 and fl_disattivo=true));





insert into impianti (id_azienda,filename_planimetria,ts_ins,id_utente_ins,fl_disattivo,descr_impianto,codice_impianto) values (39,39,'2019-12-20 08:00:00.000001',1,false,'Osoppo - VSA 4','Osoppo - VSA 4');
insert into impianti (id_azienda,filename_planimetria,ts_ins,id_utente_ins,fl_disattivo,descr_impianto,codice_impianto) values (39,39,'2019-12-20 08:00:00.000001',1,false,'Osoppo - EOX 6-7','Osoppo - EOX 6-7');
insert into impianti (id_azienda,filename_planimetria,ts_ins,id_utente_ins,fl_disattivo,descr_impianto,codice_impianto) values (39,39,'2019-12-20 08:00:00.000001',1,false,'Osoppo - Stoccaggio','Osoppo - Stoccaggio');
insert into impianti (id_azienda,filename_planimetria,ts_ins,id_utente_ins,fl_disattivo,descr_impianto,codice_impianto) values (39,39,'2019-12-20 08:00:00.000001',1,false,'Osoppo - Comuni Stabilimento','Osoppo - Comuni Stabilimento');



insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Produzione vuoto Linea 4');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Produzione Ossigeno Linea 4');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Sala Macchine Linea 4');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Compressori C41 - C42');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Cabina elettrica Linea 4');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Locale Trafo 20/0,4 kV Linea 4');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Locale Trafo 20/6kV Linea 4');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Sala controllo');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Officina/Magazzino');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - VSA 4'),'Compressore C40');



insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Produzione Ossigeno EOX 6');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Produzione vuoto EOX 6');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'EOX 6');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Compressore C46');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Produzione Ossigeno EOX 7');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Produzione vuoto EOX 7');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'EOX 7');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Compressore C47');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Cabina elettrica EOX 6-7');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Locale Trafo TR 101 EOX 6-7');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Locale Trafo TR 102 EOX 6-7');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Impianto raffreddamento acqua');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Serbatoio V80');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Locale tecnico');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Sala macchine EOX 6-7');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Compressori C46 - C47');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - EOX 6-7'),'Area esterna');



insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - Stoccaggio'),'Stoccaggio O2 Liquido');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - Stoccaggio'),'Stoccaggio N2 Liquido');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - Stoccaggio'),'Cunicolo tubazioni');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - Stoccaggio'),'Buffers ossigeno');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - Stoccaggio'),'Cabina Interconnessione');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - Stoccaggio'),'Stoccaggio');




insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - Comuni Stabilimento'),'Intero Impianto');
insert into area_lavoro (ts_ins,id_utente_ins,fl_disattivo,fl_tutto_impianto,area_simulabile_tutto_impianto,id_impianto,descr_area) values ('2019-12-20 08:00:00.000001',1,false,false,false,(select id_impianto from impianti where id_azienda=39 and fl_disattivo=false and descr_impianto='Osoppo - Comuni Stabilimento'),'Area esterna');










--Osoppo - VSA 4

insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Skid Pompe Vuoto');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'MC02 - Motore elettrico pompa vuoto');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Riduttore Lufkin');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'C02A - Pompa vuoto 1° stadio');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'C02B - Pompa vuoto 2° stadio');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Valvola / Attuatore KJV 180');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Valvola / Attuatore KJV 270');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Sensori aria ambiente');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Adsorbitori R01 - R02 - R03');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Valvole / Attuatori');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Sensori aria ambiente');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Soffiante Aria');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'MC01 - Motore elettrico');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'C01 - Soffiante aria');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'E01 - Riscaldatore');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'F01 - Filtro aria');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Valvole di regolazione');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala Macchine Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'AI 140 - Analizzatore O2');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala Macchine Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro elettrico linea 4');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala Macchine Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Strumentazione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala Macchine Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Illuminazione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala Macchine Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Carrello elevatore');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Compressori C41 - C42');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Compressore C41');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Compressore C42');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Motore elettrico MC41');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Motore elettrico MC42');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Riduttore C41');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Riduttore C42');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'PLC C41');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'PLC C42');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Serbatoio O2 Gassoso B44');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Strumentazione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Sensori aria ambiente');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C41 - C42' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Illuminazione');
                
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadri 20kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro arrivo 20 kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro misure 20 kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro partenza trafo 20/6kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro partenza trafo 20/0,4kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro arrivo trafo 20/6kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadri 6kV linea 4');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro partenza motore MC02');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'UPS Y04 - Y05');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro Rifasamento');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro distribuzione bassa tensione 380 V');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro partenza motore MC41');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro partenza motore MC42');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro luce');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro piccola forza motrice Y06');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Quadro stoccaggio');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Climatizzatore Cabina Elettrica Linea 4');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Illuminazione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale Trafo 20/0,4 kV Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Trasformatore 20/0,4 kV Linea 4');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale Trafo 20/6kV Linea 4' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Trasformatore 20/6kV Linea 4');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala controllo' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Climatizzatori Sala controllo');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala controllo' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Illuminazione');
                
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala controllo' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'PC Supervisione impianti');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala controllo' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'PLC Stoccaggio');
                
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Officina/Magazzino' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Illuminazione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C40' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - VSA 4' and fl_disattivo=false)),'Carroponte C40');
                
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
--Osoppo - EOX 6-7             
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Adsorbitori EOX 6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Analizzatore O2');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro PLC EOX 6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Valvole / Attuatori');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Carroponte EOX 6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Capacità B45-6/B46-6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Sensori aria ambiente');
                 
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Skid Pompa Vuoto');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Motore elettrico MC01-6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Soffiante aria C01-1');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Pompa vuoto C01-2');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Valvola e attuatore KJV 7018-6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Valvola e attuatore KJV 8018-6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Filtri aspirazione / silenziatore S02-1-6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Camino silenziatore B01-6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Sensori aria ambiente');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='EOX 6' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Strumentazione EOX 6');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C46' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Compressore ossigeno C46');             
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C46' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Motore elettrico MC46');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C46' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Strumentazione C46');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C46' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Carroponte C46');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C46' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Sensori aria ambiente');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C46' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Illuminazione');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Adsorbitori EOX 7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Analizzatore O2');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro PLC EOX 7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Valvole / Attuatori');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Carroponte EOX 7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Capacità B45-7/B46-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione Ossigeno EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Sensori aria ambiente');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Skid Pompa Vuoto');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Motore elettrico MC01-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Soffiante aria C01-1');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Pompa vuoto C01-2');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Valvola e attuatore KJV 7018-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Valvola e attuatore KJV 8018-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Filtri aspirazione / silenziatore S02-1-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Camino silenziatore B01-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Produzione vuoto EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Sensori aria ambiente');
 
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='EOX 7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Osoppo - VSA 7');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C47' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Compressore ossigeno C47');             
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C47' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Motore elettrico MC47');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C47' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Strumentazione C47');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C47' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Carroponte C47');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressore C47' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Illuminazione');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadri media tensione Linee 6/7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro arrivo 20 kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro partenza trafo TR 101 20/6kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro partenza trafo TR 102 20/0,4kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro arrivo trafo TR 101 20/6kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro arrivo trafo TR 102 20/0,4kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadri partenza motori 6kV');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro partenza motore C01M-6');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro partenza motore C01M-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro partenza motore MC46');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro partenza motore MC47');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro Rifasamento EOX 6-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Condensatori Rifasamento EOX 6-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Quadro distribuzione 400V');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'UPS');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Illuminazione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale Trafo TR 101 EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Trasformatore 20/6kV Linee 6/7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale Trafo TR 102 EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Trasformatore 20/0,4kV Linee 6/7');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Impianto raffreddamento acqua' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Dry cooler');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Impianto raffreddamento acqua' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Skid acqua raffreddamento');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Impianto raffreddamento acqua' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Torre acqua');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Impianto raffreddamento acqua' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Sistema dosaggio prodotti chimici');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Serbatoio V80' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Serbatoio V80');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Serbatoio V80' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Skid acqua tenute');
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale tecnico' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Impianto Aria Strumenti');                
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale tecnico' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Climatizzatore Locale tecnico');          
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale tecnico' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Sensori aria ambiente');                  
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale tecnico' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Impianto osmosi');    
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Locale tecnico' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Illuminazione'); 
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala macchine EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Serbatoio V82');        
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala macchine EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Carriponte EOX 6-7 - C46 - C47');         
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala macchine EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Illuminazione');        
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina elettrica EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Climatizzatori Cabina elettrica EOX 6-7');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Compressori C46 - C47' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),  'Impianto sprinkler');   
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Sala macchine EOX 6-7' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Carrello elevatore'); 
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Area esterna' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - EOX 6-7' and fl_disattivo=false)),'Impianto Climatizzazione EOX 6-7');       
                   
           
           
           
           
           
           
--Osoppo - Stoccaggio          
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Stoccaggio O2 Liquido' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Serbatoi stoccaggio O2 Liquido');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Stoccaggio O2 Liquido' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Vasche vaporizzazione ossigeno');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Stoccaggio O2 Liquido' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Tubazioni Ossigeno');      
                                                                                                                                                                                                                                                                                                               
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Stoccaggio N2 Liquido' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Serbatoi stoccaggio N2 Liquido');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Stoccaggio N2 Liquido' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Vasche vaporizzazione azoto');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Stoccaggio N2 Liquido' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Tubazioni Azoto');      
                                                                  
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cunicolo tubazioni' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Tubazioni Gas');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Buffers ossigeno' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Buffers ossigeno');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Buffers ossigeno' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Buffer ossigeno B40');      
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Buffers ossigeno' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Buffer ossigeno B41');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Buffers ossigeno' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Buffer ossigeno B42');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Buffers ossigeno' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Buffer ossigeno B43');                
                                                                  
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cunicolo tubazioni' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Tubazioni uscita compressori C46 - C47');
                                                                  
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina Interconnessione' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Strumentazione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina Interconnessione' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Valvole regolazione pressione di rete');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Cabina Interconnessione' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Cabina Interconnessione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Stoccaggio' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Stoccaggio' and fl_disattivo=false)),'Illuminazione');
           
           
           
           
           
           
           
           
--Osoppo - Comuni Stabilimento 
           
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Intero Impianto' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Impianto rilevazione fumi');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Intero Impianto' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Estintori-Idranti-Monitori');      
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Intero Impianto' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Lampade emergenza');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Intero Impianto' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Sensori aria ambiente');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Intero Impianto' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Sirene e allarmi acustici');      
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Intero Impianto' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Edifici');
                                                                  
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Area esterna' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Illuminazione esterna');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Area esterna' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Recinzione');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Area esterna' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Verde');
insert into equipment (fl_eis,fl_disattivo,id_area,descr_equipment) values (false,false,(select id_area from area_lavoro where descr_area='Area esterna' and fl_disattivo=false and id_impianto in (select id_impianto from impianti where descr_impianto='Osoppo - Comuni Stabilimento' and fl_disattivo=false)),'Anello circuito antincendio');    


















-- coordinate per visualizzazione
update area_lavoro set rect_x=1070, rect_y=555, rect_w=100, rect_h=55, testo_x=1070, testo_y=600, a_capo=10 	where fl_disattivo=false and descr_area='Produzione vuoto Linea 4';
update area_lavoro set rect_x=953, rect_y=630, rect_w=100, rect_h=55, testo_x=953, testo_y=675, a_capo=10 		where fl_disattivo=false and descr_area='Produzione Ossigeno Linea 4';
update area_lavoro set rect_x=1070, rect_y=405, rect_w=100, rect_h=55, testo_x=1070, testo_y=450, a_capo=10 	where fl_disattivo=false and descr_area='Sala Macchine Linea 4';
update area_lavoro set rect_x=1070, rect_y=630, rect_w=100, rect_h=55, testo_x=1070, testo_y=675, a_capo=10 	where fl_disattivo=false and descr_area='Compressori C41 - C42';
update area_lavoro set rect_x=1070, rect_y=35, rect_w=100, rect_h=55, testo_x=1070, testo_y=80, a_capo=10 		where fl_disattivo=false and descr_area='Cabina elettrica Linea 4';
update area_lavoro set rect_x=1070, rect_y=185, rect_w=100, rect_h=55, testo_x=1070, testo_y=230, a_capo=10		where fl_disattivo=false and descr_area='Locale Trafo 20/0,4 kV Linea 4';
update area_lavoro set rect_x=1070, rect_y=255, rect_w=100, rect_h=55, testo_x=1070, testo_y=300, a_capo=10		where fl_disattivo=false and descr_area='Locale Trafo 20/6kV Linea 4';
update area_lavoro set rect_x=953, rect_y=35, rect_w=100, rect_h=55, testo_x=953, testo_y=80, a_capo=10 		where fl_disattivo=false and descr_area='Sala controllo';
update area_lavoro set rect_x=1070, rect_y=110, rect_w=100, rect_h=55, testo_x=1070, testo_y=155, a_capo=10 	where fl_disattivo=false and descr_area='Officina/Magazzino';
update area_lavoro set rect_x=1070, rect_y=330, rect_w=100, rect_h=55, testo_x=1070, testo_y=375, a_capo=10 	where fl_disattivo=false and descr_area='Compressore C40';


update area_lavoro set rect_x=377, rect_y=630, rect_w=100, rect_h=55, testo_x=377, testo_y=675, a_capo=10 		where fl_disattivo=false and descr_area='Produzione Ossigeno EOX 6';
update area_lavoro set rect_x=32, rect_y=255, rect_w=100, rect_h=55, testo_x=32, testo_y=300, a_capo=10			where fl_disattivo=false and descr_area='Produzione vuoto EOX 6';
update area_lavoro set rect_x=260, rect_y=630, rect_w=100, rect_h=55, testo_x=260, testo_y=675, a_capo=10 		where fl_disattivo=false and descr_area='EOX 6';
update area_lavoro set rect_x=607, rect_y=630, rect_w=100, rect_h=55, testo_x=630, testo_y=675, a_capo=10 		where fl_disattivo=false and descr_area='Compressore C46';
update area_lavoro set rect_x=32, rect_y=480, rect_w=100, rect_h=55, testo_x=32, testo_y=525, a_capo=10 		where fl_disattivo=false and descr_area='Produzione Ossigeno EOX 7';
update area_lavoro set rect_x=32, rect_y=330, rect_w=100, rect_h=55, testo_x=32, testo_y=375, a_capo=10 		where fl_disattivo=false and descr_area='Produzione vuoto EOX 7';
update area_lavoro set rect_x=32, rect_y=405, rect_w=100, rect_h=55, testo_x=32, testo_y=450, a_capo=10 		where fl_disattivo=false and descr_area='EOX 7';
update area_lavoro set rect_x=492, rect_y=630, rect_w=100, rect_h=55, testo_x=492, testo_y=675, a_capo=10 		where fl_disattivo=false and descr_area='Compressore C47';
update area_lavoro set rect_x=145, rect_y=35, rect_w=100, rect_h=55, testo_x=145, testo_y=80, a_capo=10			where fl_disattivo=false and descr_area='Cabina elettrica EOX 6-7';
update area_lavoro set rect_x=260, rect_y=35, rect_w=100, rect_h=55, testo_x=260, testo_y=80, a_capo=10 		where fl_disattivo=false and descr_area='Locale Trafo TR 101 EOX 6-7';
update area_lavoro set rect_x=377, rect_y=35, rect_w=100, rect_h=55, testo_x=377, testo_y=80, a_capo=10 		where fl_disattivo=false and descr_area='Locale Trafo TR 102 EOX 6-7';
update area_lavoro set rect_x=722, rect_y=630, rect_w=100, rect_h=55, testo_x=722, testo_y=675, a_capo=10 		where fl_disattivo=false and descr_area='Impianto raffreddamento acqua';
update area_lavoro set rect_x=145, rect_y=630, rect_w=100, rect_h=55, testo_x=145, testo_y=675, a_capo=10 		where fl_disattivo=false and descr_area='Serbatoio V80';
update area_lavoro set rect_x=32, rect_y=110, rect_w=100, rect_h=55, testo_x=32, testo_y=155, a_capo=10 		where fl_disattivo=false and descr_area='Locale tecnico';
update area_lavoro set rect_x=32, rect_y=185, rect_w=155, rect_h=55, testo_x=32, testo_y=230, a_capo=10 		where fl_disattivo=false and descr_area='Sala macchine EOX 6-7';
update area_lavoro set rect_x=0, rect_y=0, rect_w=100, rect_h=55, testo_x=0, testo_y=0, a_capo=10 				where fl_disattivo=false and descr_area='Compressori C46 - C47';
update area_lavoro set rect_x=32, rect_y=555, rect_w=100, rect_h=55, testo_x=32, testo_y=600, a_capo=10 		where fl_disattivo=false and descr_area='Area esterna';


update area_lavoro set rect_x=607, rect_y=35, rect_w=100, rect_h=55, testo_x=607, testo_y=80, a_capo=10 		where fl_disattivo=false and descr_area='Stoccaggio O2 Liquido';
update area_lavoro set rect_x=722, rect_y=35, rect_w=100, rect_h=55, testo_x=722, testo_y=80, a_capo=10 		where fl_disattivo=false and descr_area='Stoccaggio N2 Liquido';
update area_lavoro set rect_x=837, rect_y=35, rect_w=100, rect_h=55, testo_x=837, testo_y=80, a_capo=10 		where fl_disattivo=false and descr_area='Cunicolo tubazioni';
update area_lavoro set rect_x=1070, rect_y=480, rect_w=100, rect_h=55, testo_x=1070, testo_y=525, a_capo=10 	where fl_disattivo=false and descr_area='Buffers ossigeno';
update area_lavoro set rect_x=837, rect_y=630, rect_w=100, rect_h=55, testo_x=837, testo_y=630, a_capo=10 		where fl_disattivo=false and descr_area='Cabina Interconnessione';
update area_lavoro set rect_x=492, rect_y=35, rect_w=100, rect_h=55, testo_x=492, testo_y=80, a_capo=10 		where fl_disattivo=false and descr_area='Stoccaggio';


update area_lavoro set rect_x=32, rect_y=630, rect_w=100, rect_h=55, testo_x=32, testo_y=675, a_capo=10 		where fl_disattivo=false and descr_area='Intero Impianto';
update area_lavoro set rect_x=32, rect_y=555, rect_w=100, rect_h=55, testo_x=32, testo_y=600, a_capo=10 		where fl_disattivo=false and descr_area='Area esterna';



-- coordinate per stampa
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=555, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=600, a_capo_stampa=10 	where fl_disattivo=false and descr_area='Produzione vuoto Linea 4';
update area_lavoro set rect_x_stampa=953, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=953, testo_y_stampa=675, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Produzione Ossigeno Linea 4';
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=405, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=450, a_capo_stampa=10 	where fl_disattivo=false and descr_area='Sala Macchine Linea 4';
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=675, a_capo_stampa=10 	where fl_disattivo=false and descr_area='Compressori C41 - C42';
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=80, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Cabina elettrica Linea 4';
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=185, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=230, a_capo_stampa=10		where fl_disattivo=false and descr_area='Locale Trafo 20/0,4 kV Linea 4';
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=255, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=300, a_capo_stampa=10		where fl_disattivo=false and descr_area='Locale Trafo 20/6kV Linea 4';
update area_lavoro set rect_x_stampa=953, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=953, testo_y_stampa=80, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Sala controllo';
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=110, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=155, a_capo_stampa=10 	where fl_disattivo=false and descr_area='Officina/Magazzino';
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=330, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=375, a_capo_stampa=10 	where fl_disattivo=false and descr_area='Compressore C40';


update area_lavoro set rect_x_stampa=377, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=377, testo_y_stampa=675, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Produzione Ossigeno EOX 6';
update area_lavoro set rect_x_stampa=32, rect_y_stampa=255, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=300, a_capo_stampa=10			where fl_disattivo=false and descr_area='Produzione vuoto EOX 6';
update area_lavoro set rect_x_stampa=260, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=260, testo_y_stampa=675, a_capo_stampa=10 		where fl_disattivo=false and descr_area='EOX 6';
update area_lavoro set rect_x_stampa=607, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=630, testo_y_stampa=675, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Compressore C46';
update area_lavoro set rect_x_stampa=32, rect_y_stampa=480, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=525, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Produzione Ossigeno EOX 7';
update area_lavoro set rect_x_stampa=32, rect_y_stampa=330, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=375, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Produzione vuoto EOX 7';
update area_lavoro set rect_x_stampa=32, rect_y_stampa=405, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=450, a_capo_stampa=10 		where fl_disattivo=false and descr_area='EOX 7';
update area_lavoro set rect_x_stampa=492, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=492, testo_y_stampa=675, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Compressore C47';
update area_lavoro set rect_x_stampa=145, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=145, testo_y_stampa=80, a_capo_stampa=10			where fl_disattivo=false and descr_area='Cabina elettrica EOX 6-7';
update area_lavoro set rect_x_stampa=260, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=260, testo_y_stampa=80, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Locale Trafo TR 101 EOX 6-7';
update area_lavoro set rect_x_stampa=377, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=377, testo_y_stampa=80, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Locale Trafo TR 102 EOX 6-7';
update area_lavoro set rect_x_stampa=722, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=722, testo_y_stampa=675, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Impianto raffreddamento acqua';
update area_lavoro set rect_x_stampa=145, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=145, testo_y_stampa=675, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Serbatoio V80';
update area_lavoro set rect_x_stampa=32, rect_y_stampa=110, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=155, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Locale tecnico';
update area_lavoro set rect_x_stampa=32, rect_y_stampa=185, rect_w_stampa=155, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=230, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Sala macchine EOX 6-7';
update area_lavoro set rect_x_stampa=0, rect_y_stampa=0, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=0, testo_y_stampa=0, a_capo_stampa=10 				where fl_disattivo=false and descr_area='Compressori C46 - C47';
update area_lavoro set rect_x_stampa=32, rect_y_stampa=555, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=600, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Area esterna';


update area_lavoro set rect_x_stampa=607, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=607, testo_y_stampa=80, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Stoccaggio O2 Liquido';
update area_lavoro set rect_x_stampa=722, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=722, testo_y_stampa=80, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Stoccaggio N2 Liquido';
update area_lavoro set rect_x_stampa=837, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=837, testo_y_stampa=80, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Cunicolo tubazioni';
update area_lavoro set rect_x_stampa=1070, rect_y_stampa=480, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=1070, testo_y_stampa=525, a_capo_stampa=10 	where fl_disattivo=false and descr_area='Buffers ossigeno';
update area_lavoro set rect_x_stampa=837, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=837, testo_y_stampa=630, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Cabina Interconnessione';
update area_lavoro set rect_x_stampa=492, rect_y_stampa=35, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=492, testo_y_stampa=80, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Stoccaggio';


update area_lavoro set rect_x_stampa=32, rect_y_stampa=630, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=675, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Intero Impianto';
update area_lavoro set rect_x_stampa=32, rect_y_stampa=555, rect_w_stampa=100, rect_h_stampa=55, testo_x_stampa=32, testo_y_stampa=600, a_capo_stampa=10 		where fl_disattivo=false and descr_area='Area esterna';