ALTER TABLE PDL ADD COLUMN V9_ATTREZZATURA_INSTALLAZIONE_OGGETTO character varying(255);
ALTER TABLE PDL ADD COLUMN V9_ATTREZZATURA_INSTALLAZIONE_SICUREZZA character varying(255);
ALTER TABLE PDL ADD COLUMN V9_NOMINATIVO_RICHIEDENTE character varying(255);
ALTER TABLE PDL ADD COLUMN V9_ALTRO_SEZ1_ATTIVITA1_TESTO character varying(255);

ALTER TABLE PDL ADD COLUMN FLG_V9_ELETTRICA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_CHIMICA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_PRESSIONE BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_IDRAULICA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_SOST_PERICOLOSE BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_ALTRA_ENERG_MECC BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_TERMICA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_SOST_INFIAMMABILI_ESPLOSIVE BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_ALTEZZA_INF_2M BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_ALTEZZA_SUP_2M BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_SOLLEVAMENTI BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_ALTRO BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_APP_CAVI_ELETTRICI BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_SPAZI_ANGUSTI BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_MICROCLIMA BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE PDL ADD COLUMN FLG_V9_ISOLARE BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_PULIZIA_OSSIGENO BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_SOFFIAGGIO_AZOTO BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_SOFFIAGGIO_ARIA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_VENTILAZIONE_FORZATA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_ANALIZZATORE_GAS_TOSSICI BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_PROTEGGERE_CADITOIE_TOMBINI BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_SUPERVISIONE_DELEGATO_LAVORI_AL BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_VISIONARE_SCHEDE_SICUREZZA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_VISIONARE_DOCUMENTI_SITO BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_PDL_A_CALDO BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_SALDATURA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_TAGLIO_MOLATURA BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_VERIFICA_PIANO_SOLLEVAMENTO BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE PDL ADD COLUMN FLG_V9_PRODUZIONE_RIFIUTI_DA_CARATTERIZZARE BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE PDL ADD COLUMN V9_ALTRO_SEZ1_DISPOSITIVI_PROTEZIONE character varying(255);
ALTER TABLE PDL ADD COLUMN V9_SEZ2_ALTRO_MISURE_SICUREZZA character varying(255);
ALTER TABLE PDL ADD COLUMN V9_SEZ2_RISCHI_SPECIFICI_NOMINATIVO character varying(255);
ALTER TABLE PDL ADD COLUMN V9_ALTRO_SEZ1_ASPETTI_AMBIENTALI character varying(255);
ALTER TABLE PDL ADD COLUMN V9_ALTRO_SEZ1_PERICOLO_RISCHIO character varying(255);

ALTER TABLE PDL ADD COLUMN REVISIONE character varying(10);

ALTER TABLE PDL ADD COLUMN MOTIVAZIONE character varying(255);

ALTER TABLE PDL ADD COLUMN ID_V9_NOMINATIVO_RICHIEDENTE int;
ALTER TABLE PDL ADD COLUMN ID_V9_SEZ2_RISCHI_SPECIFICI_NOMINATIVO int;