DROP VIEW IF EXISTS v_parametri cascade  ;
DROP VIEW IF EXISTS V_PDL cascade;
DROP VIEW IF EXISTS v_alimod20_dettaglio cascade;
DROP VIEW IF EXISTS v_alimod80 cascade;
DROP VIEW IF EXISTS v_alimod50 cascade;
DROP VIEW IF EXISTS v_alimod20 cascade;
DROP VIEW IF EXISTS v_alimod67 cascade;
DROP VIEW IF EXISTS v_allestimenti cascade;
DROP VIEW IF EXISTS v_specifiche_allestimenti  cascade;
DROP VIEW IF EXISTS v_sitiquse_bl   cascade;


ALTER TABLE PARAMETRI ALTER COLUMN DESCRIZIONE TYPE VARCHAR;


DELETE FROM parametri WHERE DOMINIO ='TPC' OR (DOMINIO ='DOM' AND CODICE='TPC');
insert into parametri (dominio,codice,descrizione) values ('DOM','TPC','Tipo di comunicazione');
insert into parametri (dominio,codice,descrizione,ordine) values ('TPC','C01','Comunicazione di Crisi',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('TPC','C02','IPG (Incidente di Sicurezza Potenzialmente Grave)',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('TPC','C03','Infortunio',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('TPC','C04','Incidente di trasporto',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('TPC','C05','Incidente ambientale',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('TPC','C06','Incidente di Affidabilità Altro incidente',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('TPC','C07','Mancato Incidente',7);

DELETE FROM parametri WHERE DOMINIO ='TIM' OR (DOMINIO ='DOM' AND CODICE='TIM');
insert into parametri (dominio,codice,descrizione) values ('DOM','TIM','Tipo di impianto');
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T01','Acetylene plant/Impianto Acetilene',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T02','ASU',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T03','Chemical Site/Sito chimico',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T04','CO2 plant/Impianto CO2',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T05','Cogen unit/Unità di cogenerazione',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T06','Customer Installation/Installazione in Clientela',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T07','Gas filling/Condizionamento Gas',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T08','Head Office/Sede',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T09','Home/Casa',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T10','Homecare Environment/Ambiente Cure a Domicilio',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T11','Hospital/Ospedale',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T12','HPU/Unità di produzione H2',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T13','HYCO unit/Unità di produzione HYCO',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T14','Offices/Uffici',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T15','Pipelines/Tubazioni',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T16','Research center/Centro di ricerca',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T17','TGCM',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T18','Transportation (road, rail, airplane, boat, …)/Trasporto (strada, ferrovia, aereo, nave, …)',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T19','Unknown/Sconosciuto',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T20','Warehouse/Magazzino-deposito',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T21','Welding plant/Impianto Saldatura',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T22','Workshop/Officina',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIM','T23','Other/Altro',23);

DELETE FROM parametri WHERE DOMINIO ='NEV' OR (DOMINIO ='DOM' AND CODICE='NEV');
insert into parametri (dominio,codice,descrizione) values ('DOM','NEV','Natura dell''evento');
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N01','Agression/Aggressione',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N02','Burst/Scoppio',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N03','Circulation (excluding delivery)/Circolazione (escluse consegne)',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N04','Crushing/Impatto, urto',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N05','Cut/Taglio',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N06','Equipment failure/Guasto apparecchiatura',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N07','Explosion/Esplosione',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N08','External cause/Causa esterna',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N09','Fall/Caduta',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N10','Fire/Fuoco, incendio',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N11','Leak/Perdita',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N12','Pain/Dolore',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N13','Shock',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N14','Transport (delivery)/Trasporto (consegna)',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N15','Unkown/Sconosciuto',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('NEV','N16','Other/Altro',16);

DELETE FROM parametri WHERE DOMINIO ='PPE' OR (DOMINIO ='DOM' AND CODICE='PPE');
insert into parametri (dominio,codice,descrizione) values ('DOM','PPE','Prodotto pertinente all''evento');
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P01','Product is irrelevant/Il prodotto è irrilevante',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P02','Product is unidentified/Prodotto non identificato',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P03','Acetone',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P04','Acetylene/Acetilene',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P05','Acids/Acidi',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P06','Alkali/Basi',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P07','Ammonia/Ammoniaca',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P08','Ammonium Nitrate/Nitrato di Ammonio',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P09','Argon',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P10','Arsine/Arsina',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P11','Calcium Carbide/Carburo di Calcio',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P12','Calcium Carbide Dust/Polvere di Carburo di Calcio',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P13','Carbon Dioxide/Diossido di Carbonio',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P14','Carbon Monoxide/Monossido di Carbonio',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P15','Catalysts/Catalizzatori',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P16','Chlorine/Cloro',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P17','Compressed Air/Aria Compressa',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P18','Dessicants/Essiccanti',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P19','Diatomaceous Earth "monkey dust"/Farina fossile',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P20','DMF',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P21','Dry Ice/Ghiaccio Secco',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P22','Electricity/Elettricità',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P23','Flammable Gas Mixture/Miscela Gassosa infiammabile ',23);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P24','Fuel-Oxidizer Mixture/Miscela Combustibile-Comburente',24);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P25','Fuels/Combustibili',25);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P26','Fumes/Vapori',26);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P27','Gaseous Fluorine/Fluoro gassoso',27);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P28','Halocarbons/ Idrocarburi Alogenati gassosi',28);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P29','Helium/Elio',29);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P30','Hydrogen/Idrogeno',30);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P31','Hydrogen Chloride/Acido cloridrico',31);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P32','Hydrogen Fluoride/Acido fluoridrico',32);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P33','Hydrogen Peroxyde/Perossido di Idrogeno (Acqua Ossigenata)',33);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P34','Lime/Calce',34);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P35','Liq. Ammonia/Ammoniaca liquida',35);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P36','Liq. Argon/Argon liquido',36);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P37','Liq. Carbon Dioxide/Diossido di Carbonio liquido',37);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P38','Liq. Halocarbons/Idrocarburi Alogenati liquidi',38);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P39','Liq. Helium/Elio liquido',39);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P40','Liq. Hydrogen/Idrogeno liquido',40);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P41','Liq. Nitrogen/Azoto liquido',41);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P42','Liq. Nitrous Oxide/Protossido di Azoto liquido',42);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P43','Liq. Oxygen/Ossigeno liquido',43);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P44','LPG/GPL',44);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P45','Lubricants Liquid/Lubrificanti liquidi',45);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P46','Lubricants Solid/Lubrificanti solidi',46);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P47','Molecular Sieves/Setacci Molecolari',47);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P48','Nitric Oxide/Ossido di Azoto',48);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P49','Nitrogen/Azoto',49);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P50','Nitrogen Trifluoride/Trifluoruro di Azoto',50);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P51','Nitrous Oxide/Protossido di Azoto',51);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P52','Non-flammable Gas Mixture/Miscela Gassosa non infiammabile',52);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P53','Odorizing Agents/Agenti Odorizzanti',53);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P54','Other Bulk Liquid Product/Altri Prodotti liquidi in bulk',54);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P55','Other chemical-material/Altri Prodotti chimici-materiali',55);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P56','Other Corrosive Gases/Altri Gas corrosivi',56);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P57','Other Flammable/Pyrophoric Gases/Altri Gas infiammabili-piroforici',57);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P58','Other Gaseous Products/Altri Prodotti Gassosi',58);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P59','Other Heat Insulation/Altri Isolanti Termici',59);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P60','Other Medical Gases/Altri Gas Medicinali',60);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P61','Other Solid products/Altri Prodotti solidi',61);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P62','Other Toxic Gases/Altri Gas tossici',62);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P63','Other utility/Altri Servizi',63);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P64','Oxygen/Ossigeno',64);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P65','Ozone/Ozono',65);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P66','Paints/Vernici',66);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P67','Perlite',67);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P68','Phosphine/Fosfina',68);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P69','Rare Gas (Ne, Kr, Xe)/Gas rari (Ne, Kr, Xe)',69);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P70','Scrubber Solution/Soluzione per scrubber',70);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P71','Silane/Silano',71);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P72','Solvents/Solventi',72);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P73','Steam/Vapore',73);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P74','SynGas/Gas di sintesi',74);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P75','Synthetic Air/Aria Sintetica (ricostituita)',75);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P76','Tungsten Hexafluoride/Esafluoruro di Tungsteno ',76);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P77','Vacuum/Vuoto',77);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P78','Waste-Refuse/Rifiuti-Scarti',78);
insert into parametri (dominio,codice,descrizione,ordine) values ('PPE','P79','Water/Acqua',79);

DELETE FROM parametri WHERE DOMINIO ='A80' OR (DOMINIO ='DOM' AND CODICE='A80');
insert into parametri (dominio,codice,descrizione) values ('DOM','A80','Azioni ALI-MOD 80');
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A01','Activity is irrelevant/L''attività è irrilevante',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A02','Unidentified activity/Attività non identificata',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A03','Building/Costruzione',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A04','Calibrating/Taratura',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A05','Civil Work/Lavori civili',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A06','Cleaning/Pulizia',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A07','Climbing-Going Down/Salita-Discesa',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A08','Closing Valve/Chiusura valvole',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A09','Connect wrong product container/Connessione tra contenitori errati di prodotto',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A10','Connecting/Collegamento',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A11','Delivering Wrong Product/Consegna prodotto sbagliato',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A12','Draining/Drenaggio',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A13','Driving/Guida',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A14','Emergency Shutdown/Fermata di emergenza',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A15','Filling/Riempimento',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A16','Grinding/Molatura',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A17','Handling/Movimentazione',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A18','Handling (manual)/Movimentazione (manuale)',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A19','Handling (mechanical assistance)/Movimentazione (assistenza meccanica)',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A20','Handling Material/Movimentazione di materiale',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A21','Home-Office Equipment Installation/Installazione attrezzatura per casa-ufficio',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A22','Home-Work Commuting/Trasferimento casa-lavoro',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A23','Housekeeping/Ordine e pulizia',23);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A24','Industrial Equipment/Attrezzature industriali',24);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A25','Inerting/Inertizzazione',25);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A26','Inspecting -Testing (cylinders)/Ispezione-Revisione periodica (bombole)',26);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A27','Inspecting-Testing (vessel, equipment)/Ispezione-Collaudo (recipienti, attrezzature)',27);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A28','Leisure/Tempo libero',28);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A29','Loading/Carico',29);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A30','Measuring/Misurazione',30);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A31','Mixing-Polluting/Miscelazione-Inquinamento',31);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A32','Monitoring/Monitoraggio',32);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A33','Opening valve/Apertura valvole',33);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A34','Order Processing/Elaborazione ordini',34);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A35','Other construction activity/Altre attività di costruzione',35);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A36','Other delivering non conformity/Altre non conformità nella consegna',36);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A37','Other maintenance activity/Altre attività di manutenzione',37);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A38','Other misuse of product/Altri utilizzi non corretti di prodotto',38);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A39','Other off the job activity/Altra attività non lavorativa',39);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A40','Other operating activity/Altre attività operative',40);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A41','Other posture/Altre condizioni',41);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A42','Other support activity/Altre attività di supporto',42);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A43','Painting/Verniciatura',43);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A44','Product-Storage Contamination/Contaminazione prodotto-stoccaggio',44);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A45','Purchasing/Acquisti',45);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A46','Recreational Activities/Attività ricreative',46);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A47','Regular Operation/Esercizio regolare',47);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A48','Regular Shutdown/Fermata regolare',48);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A49','Running/Marcia',49);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A50','Select wrong product/Scelta di prodotto sbagliato',50);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A51','Sitting/Riunione',51);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A52','Start-up/Avviamento',52);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A53','Training/Formazione',53);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A54','Travelling/Viaggio',54);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A55','Unloading/Scarico',55);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A56','Using a Tool/Utilizzo di utensili',56);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A57','Visiting/Visita',57);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A58','Walking/Camminare',58);
insert into parametri (dominio,codice,descrizione,ordine) values ('A80','A59','Welding-Soldering/Saldatura',59);

DELETE FROM parametri WHERE DOMINIO ='GGE' OR (DOMINIO ='DOM' AND CODICE='GGE');
insert into parametri (dominio,codice,descrizione) values ('DOM','GGE','Giorni Evento');
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G01','0',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G02','1',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G03','2',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G04','3',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G05','4',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G06','5',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G07','6',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G08','7',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G09','8',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G10','9',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G11','10',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G12','11',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G13','12',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G14','13',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G15','14',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G16','15',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G17','16',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G18','17',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G19','18',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G20','19',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G21','20',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G22','21',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G23','22',23);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G24','23',24);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G25','24',25);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G26','25',26);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G27','26',27);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G28','27',28);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G29','28',29);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G30','29',30);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G31','30',31);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G32','31',32);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G33','32',33);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G34','33',34);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G35','34',35);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G36','35',36);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G37','36',37);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G38','37',38);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G39','38',39);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G40','39',40);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G41','40',41);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G42','41',42);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G43','42',43);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G44','43',44);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G45','44',45);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G46','45',46);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G47','46',47);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G48','47',48);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G49','48',49);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G50','49',50);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G51','50',51);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G52','51',52);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G53','52',53);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G54','53',54);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G55','54',55);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G56','55',56);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G57','56',57);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G58','57',58);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G59','58',59);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G60','59',60);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G61','60',61);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G62','61',62);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G63','62',63);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G64','63',64);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G65','64',65);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G66','65',66);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G67','66',67);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G68','67',68);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G69','68',69);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G70','69',70);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G71','70',71);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G72','71',72);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G73','72',73);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G74','73',74);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G75','74',75);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G76','75',76);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G77','76',77);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G78','77',78);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G79','78',79);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G80','79',80);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G81','80',81);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G82','81',82);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G83','82',83);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G84','83',84);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G85','84',85);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G86','85',86);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G87','86',87);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G88','87',88);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G89','88',89);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G90','89',90);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G91','90',91);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G92','91',92);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G93','92',93);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G94','>3 mths/>3 mesi',94);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G95','>6 mths/>6 mesi',95);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGE','G96','>1 year/>1 anno',96);

DELETE FROM parametri WHERE DOMINIO ='OOE' OR (DOMINIO ='DOM' AND CODICE='OOE');
insert into parametri (dominio,codice,descrizione) values ('DOM','OOE','Ore Evento');
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O01','0',0);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O02','1',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O03','2',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O04','3',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O05','4',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O06','5',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O07','6',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O08','7',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O09','8',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O10','9',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O11','10',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O12','11',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O13','12',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O14','13',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O15','14',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O16','15',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O17','16',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O18','17',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O19','18',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O20','19',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O21','20',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O22','21',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O23','22',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('OOE','O24','23',23);

DELETE FROM parametri WHERE DOMINIO ='MME' OR (DOMINIO ='DOM' AND CODICE='MME');
insert into parametri (dominio,codice,descrizione) values ('DOM','MME','Minuti Evento');
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M01','0',0);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M02','1',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M03','2',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M04','3',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M05','4',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M06','5',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M07','6',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M08','7',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M09','8',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M10','9',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M11','10',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M12','11',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M13','12',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M14','13',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M15','14',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M16','15',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M17','16',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M18','17',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M19','18',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M20','19',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M21','20',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M22','21',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M23','22',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M24','23',23);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M25','24',24);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M26','25',25);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M27','26',26);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M28','27',27);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M29','28',28);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M30','29',29);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M31','30',30);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M32','31',31);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M33','32',32);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M34','33',33);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M35','34',34);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M36','35',35);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M37','36',36);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M38','37',37);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M39','38',38);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M40','39',39);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M41','40',40);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M42','41',41);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M43','42',42);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M44','43',43);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M45','44',44);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M46','45',45);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M47','46',46);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M48','47',47);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M49','48',48);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M50','49',49);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M51','50',50);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M52','51',51);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M53','52',52);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M54','53',53);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M55','54',54);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M56','55',55);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M57','56',56);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M58','57',57);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M59','58',58);
insert into parametri (dominio,codice,descrizione,ordine) values ('MME','M60','59',59);

DELETE FROM parametri WHERE DOMINIO ='CPE' OR (DOMINIO ='DOM' AND CODICE='CPE');
insert into parametri (dominio,codice,descrizione) values ('DOM','CPE','Categoria del personale');
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C01','Contractor (Non Main)/Fornitore di Servizi (NON Principale Fornitore di Servizi)',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C02','Main Contractor/Principale Fornitore di Servizi (vedere ALI-GT-PR-HSE-003)',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C03','Customer/Cliente',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C04','Experienced AL Employee/Dipendente AL con esperienza',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C05','New AL Employee/Neoassunto AL',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C06','New to the Job AL Employee/Dipendente AL con nuova mansione',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C07','Patient/Paziente',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C08','Temporary Worker (non AL payroll)/Lavoratore Interinale (non a libro paga AL)',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C09','Temporary Worker (AL payroll)/Lavoratore Interinale (a libro paga AL)',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C10','Third Party/Terza Parte',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('CPE','C11','Trainee/Stagista',11);

DELETE FROM parametri WHERE DOMINIO ='TIF' OR (DOMINIO ='DOM' AND CODICE='TIF');
insert into parametri (dominio,codice,descrizione) values ('DOM','TIF','Tipo di infortunio');
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T01','Fatality/Decesso',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T02','Commuting Fatality/Decesso in itinere',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T03','Lost Time Accident (LTA)/Infortunio con fermata',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T04','Lost Time Commuting Accident/Infortunio in Itinere con fermata',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T05','Modified Duty/Mansione Agevolata',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T06','Non Lost Time Accident (NLTA)/Infortunio senza fermata',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T07','Non Lost Time Commuting Accident/Infortunio in Itinere senza fermata',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T08','Non Occupational Related/Infortunio non correlato al lavoro',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T09','Occupational Disease/Malattia Professionale',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('TIF','T10','First Aid Incident/Infermeria',10);

DELETE FROM parametri WHERE DOMINIO ='ATI' OR (DOMINIO ='DOM' AND CODICE='ATI');
insert into parametri (dominio,codice,descrizione) values ('DOM','ATI','Attrezzatura interessata');
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A01','Irrelevant/Irrilevante',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A02','Absorber-Adsorber/Absorbitore-Adsorbitore',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A03','Analysers/Analizzatore',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A04','Analytical & Diagnosis Equipment/Apparecchiatura per analisi e diagnostica',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A05','Automobile',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A06','Blower/Soffiante',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A07','Booster',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A08','Bundle-pack of cylinders/Pacco-cesto di bombole',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A09','Cold Box',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A10','Compressor/Compressore',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A11','Control System-DCS/Sistema di Controllo-DCS',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A12','Cooling Tower/Torre di raffredamento',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A13','Crane-Hoisting Equipment (any type)/Gru-mezzi di sollevamento di qualsiasi tipo',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A14','Cryogenic Storage Tank/Serbatoio di stoccaggio criogenico',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A15','Cryogenic vessel/Contenitore criogenico',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A16','Cylinder/Bombola',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A17','Cylinders Filling Rack/Cestello per riempimento bombole',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A18','Demin Water unit/Unità acque demi',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A19','Deoxo',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A20','Distillation Column/Colonna di distillazione',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A21','Drum/Fusto',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A22','Dry Ice Pellets Machine/Macchina per ghiaccio secco in pellet',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A23','Dry Ice Press/Pressa per Ghiaccio Secco',23);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A24','Dryer/Essiccatore',24);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A25','Electrical Equipment/System - Apparecchiatura/Sistema Elettrico',25);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A26','Electrolyzer/Elettrolizzatore',26);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A27','Fan/Ventilatore',27);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A28','Filter (vessel)/Filtro (recipiente)',28);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A29','Forklift Truck/Carrello elevatore',29);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A30','Freezer',30);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A31','Front end purification/Purificazione in testa',31);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A32','Furnace/Forno',32);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A33','Gas Cabinet/VMP/VMB ',33);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A34','Gas Holder/Polmone gas',34);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A35','Gas Turbine/Turbina a gas',35);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A36','Generator/Generatore',36);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A37','Heat Exchanger/Scambiatore di calore',37);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A38','Heat recovery boiler/Caldaia recupero calore',38);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A39','Hopper/Tramoggia',39);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A40','Instrumentation/Strumentazione',40);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A41','Liquid Vaporizer/Vaporizzatore liquido',41);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A42','MDEA CO2 removal unit/Unità di rimozione CO2 con MDEA',42);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A43','Medical concentrator/Concentratore medicale',43);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A44','Medical CPAP/CPAP medicale',44);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A45','Medical Device/Apparecchiatura medicale',45);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A46','Medical Ventilator/Ventilatore medicale',46);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A47','Membrane/Membrana',47);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A48','Metering Station/Punto di misura',48);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A49','Motor/Motore',49);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A50','Non-cryogenic Storage Tank/Serbatoio di stoccaggio non criogenico',50);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A51','Non-electrical equipment-system/Apparecchiatura-sistema non elettrico',51);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A52','Other Application Equipment/Altre apparecchiature applicative',52);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A53','Other Auxiliary Equipment/Altre apparecchiature ausiliarie',53);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A54','Other Equipment-Machinery/Altre apparecchiature-macchinari',54);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A55','Other Gas Processing and Transfer/Altre apparecchiature di processo e trasferimento gas',55);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A56','Other Handling Equipment/Altre apparecchiature per la movimentazione',56);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A57','Other Portable Vessel/Altri contenitori portatili',57);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A58','Other Storage Vessel/Altri contenitori per stoccaggio',58);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A59','Other Tools/Altri attrezzi',59);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A60','Other Transport Equipment/Altre apparecchiature per il trasporto',60);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A61','Patient Liquide Base Unit/ Unità base liquido paziente',61);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A62','Pipeline/Tubazione',62);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A63','Portable Tool/Utensile portatile',63);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A64','Pressure Vessel/Recipiente in pressione',64);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A65','PSA',65);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A66','Pump/Pompa',66);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A67','Purifier/Depuratore',67);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A68','Rail Tanker/Cassa mobile',68);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A69','Reactor/Reattore',69);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A70','Reboiler/Main Condenser - Condensatore Principale',70);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A71','Reformer',71);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A72','Separator/Separatore',72);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A73','Service Van/Furgoncino di servizio',73);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A74','Stationary Tool/Utensile fisso',74);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A75','Steam Boiler/Caldaia a vapore',75);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A76','Third Party Closed Vehicle/Veicolo chiuso di terza parte',76);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A77','Tractor/Trattore',77);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A78','Transformer/Trasformatore',78);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A79','Truck-Trailer (cylinder transport)/Autocarro-Autoarticolato (trasporto bombole)',79);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A80','Truck-Trailer (liquified gas)/Autocarro-Autoarticolato (gas liquefatti)',80);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A81','Tube Trailer/Carro bombolaio',81);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A82','Unidentified Equipment/Apparecchiatura non identificata',82);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A83','UPS (Uninterruptable Power Supply)/Gruppo di continuità',83);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A84','Vacuum Pump/Pompa a vuoto',84);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A85','Valves/Valvole',85);
insert into parametri (dominio,codice,descrizione,ordine) values ('ATI','A86','Welding Equipment/Apparecchiature per la saldatura',86);

DELETE FROM parametri WHERE DOMINIO ='CAI' OR (DOMINIO ='DOM' AND CODICE='CAI');
insert into parametri (dominio,codice,descrizione) values ('DOM','CAI','Componente attr. Interessata');
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C01','Irrelevant/Irrilevante',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C02','Analyzer/Analizzatore',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C03','Axles, Suspension/Assi, sospensione',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C04','Bearing/Cuscinetto',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C05','Brakes/Freni',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C06','Bursting Disk/Disco di rottura',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C07','Cable/Cavo',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C08','Casing/Telaio',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C09','Check Valve/Valvola di non ritorno',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C10','Circuit Breaker/Interruttore',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C11','Connection Box/Scatola di giunzione',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C12','Control Valve/Valvola di controllo',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C13','Cylinder Valve/Valvola di bombola',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C14','DCS Component/Componente Sistema di Controllo DCS',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C15','Electrical Motor/Motore elettrico',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C16','Engine/Motore',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C17','Expansion Device/Dispositivo di espansione',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C18','Filter-Strainer/Filtro-Depuratore',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C19','Flame Arrestor/Dispositivo anti fiamma',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C20','Flanges, Union, Coupling/Flange, Raccordo, Giunto',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C21','Fuse Plug/Fusibile a tappo',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C22','Gears/Ingranaggi',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C23','Grating/Griglia',23);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C24','Grounding, Bonding /Messa a terra, Collegamento',24);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C25','HP Flexible Hose-Pigtail (gas)/Manichetta Flessibile AP - (gas)',25);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C26','Hydraulic-Pneumatic System/Sistema Idraulico-Pneumatico ',26);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C27','Impeller/Ventola',27);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C28','Level Control/Controllo di livello',28);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C29','Lights/Luci ',29);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C30','Liquid Product transfer Hose/Manichetta trasferimento prodotto liquido',30);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C31','LP Flexible Hose (liquid)/Manichetta flessibile BP (liquido)',31);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C32','Lubrication System/Sistema di lubrificazione',32);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C33','Manual Valve/Valvola Manuale',33);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C34','Other component or part/Altro componente o altra parte',34);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C35','Other electrical component/Altri componenti elettrici',35);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C36','Other instrumentation-control/Altra strumentazione-controllo',36);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C37','Other mechanical component/Altro componente meccanico ',37);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C38','Other non ground level equipment/Altre apparecchiature non a livello del suolo',38);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C39','Other piping part or fitting/Altre tubazioni o attrezzature',39);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C40','Other valve/Altre valvole',40);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C41','Permanent Ladder/Scala fissa',41);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C42','Pipe-Tube/Tubazione',42);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C43','Piston/Pistone',43);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C44','Pit/Pozzetto',44);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C45','Platform/Piattaforma',45);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C46','PLC Element/Elementi di PLC',46);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C47','Portable Ladder/Scala portatile',47);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C48','Power Supply/Sorgente di energia',48);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C49','Pressure Control/Controllo di pressione',49);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C50','Pressure Gauge/Misuratore di pressione',50);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C51','Pressure Regulator Body/Regolatore di pressione: corpo',51);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C52','Pressure Regulator MembraneRegolatore di pressione: membrana',52);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C53','Pressure Regulator Other/Regolatore di pressione: altro',53);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C54','Pressure Relief Valve/Valvola regolatrice di pressione',54);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C55','Printed Wiring Board/Circuito stampato',55);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C56','Railing/Parapetto',56);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C57','Reduction/Riduzione',57);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C58','Relay/Relé',58);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C59','Safety Cable/Cavo di sicurezza',59);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C60','Scaffolding/Ponteggio',60);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C61','Seal Gas System/Sistema gas di tenuta',61);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C62','Speed Control/Controllo di velocità',62);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C63','Switch Gear/Dispositivo di fermata',63);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C64','Temperature Control/Controllo di temperatura',64);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C65','Temperature Indicator/Indicatore di temperatura',65);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C66','Transformer/Trasformatore',66);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C67','Transmitter/Trasmettitore',67);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C68','Unidentified Component or Part/Componente o parte non identificate',68);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C69','Valve Actuator/Attuatore di valvola',69);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C70','Valve Positionner/Posizionatore di valvola',70);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C71','Vibrations Control/Controllo delle vibrazioni',71);
insert into parametri (dominio,codice,descrizione,ordine) values ('CAI','C72','Wheel, Tire/Ruota, Pneumatico',72);

DELETE FROM parametri WHERE DOMINIO ='GGP' OR (DOMINIO ='DOM' AND CODICE='GGP');
insert into parametri (dominio,codice,descrizione) values ('DOM','GGP','Giorni persi presunti (prognosi)');
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G01','1 day/giorno',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G02','2 days/giorni',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G03','3 days/giorni',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G04','4 days/giorni',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G05','5 days/giorni',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G06','6 days/giorni',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G07','1 week/settimana',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G08','8 days/giorni',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G09','9 days/giorni',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G10','10 days/giorni',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G11','11days/giorni',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G12','12 days/giorni',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G13','13 days/giorni',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G14','2 weeks/settimane',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G15','15 days/giorni',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G16','16 days/giorni',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G17','17 days/giorni',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G18','18 days/giorni',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G19','19 days/giorni',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G20','20 days/giorni',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G21','3 weeks/settimane',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G22','22 days/giorni',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G23','23 days/giorni',23);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G24','24 days/giorni',24);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G25','25 days/giorni',25);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G26','26 days/giorni',26);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G27','27 days/giorni',27);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G28','28 days/giorni',28);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G29','29 days/giorni',29);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G30','30 days/giorni',30);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G31','31 days/giorni',31);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G32','1 month/mese ',32);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G33','2 months/mesi ',33);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G34','3 months/mesi',34);
insert into parametri (dominio,codice,descrizione,ordine) values ('GGP','G35','> 3 months/mesi',35);

DELETE FROM parametri WHERE DOMINIO ='LES' OR (DOMINIO ='DOM' AND CODICE='LES');
insert into parametri (dominio,codice,descrizione) values ('DOM','LES','Lesioni');
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L01','Amputation/Amputazione',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L02','Anoxia/Anossia',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L03','Asphyxiation/Asfissia',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L04','Bleeding/Emorragia',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L05','Bruise/Contusione',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L06','Burn/Ustione',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L07','Crush/Frantumazione',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L08','Cut/Taglio',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L09','Dermatitis/Dermatite',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L10','Fracture/Frattura',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L11','Hearing Damage/Danni all''udito',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L12','Hernia/Ernia',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L13','Inflammation/Infiammazione',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L14','Internal Lesion/Lesioni interne',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L15','Intoxication/Intossicazione',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L16','Irradiation/Irradiazione',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L17','Multiple Injuries/Lesioni multiple',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L18','Scratch/Graffio, escoriazione',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L19','Sight Damage/Danni alla vista',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L20','Twist, Sprain, Dislocation/Storta, distorsione, slogatura',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L21','Unidentified Injury/Lesioni non identificate',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('LES','L22','Other injury/Altre lesioni',22);

DELETE FROM parametri WHERE DOMINIO ='PCO' OR (DOMINIO ='DOM' AND CODICE='PCO');
insert into parametri (dominio,codice,descrizione) values ('DOM','PCO','Parti del corpo');
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P01','Abdomen/Addome',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P02','Ankle/Caviglia',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P03','Arm/Braccio',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P04','Back/Schiena',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P05','Elbow/Gomito',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P06','Eyes/Occhi',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P07','Face/Viso',7);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P08','Finger/Dito',8);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P09','Foot/Piede',9);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P10','Forearm/Avambraccio',10);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P11','Forehead/Fronte',11);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P12','Hand/Mano',12);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P13','Hip/Fianco',13);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P14','Knee/Ginocchio',14);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P15','Leg/Gamba',15);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P16','Multiple parts of the body/Più parti del corpo',16);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P17','Neck/Collo',17);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P18','Shoulder/Spalla',18);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P19','Skull/Cranio',19);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P20','Thigh/Coscia',20);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P21','Thorax/Torace',21);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P22','Thumb/Pollice',22);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P23','Toe/Dito del piede',23);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P24','Wrist/Polso',24);
insert into parametri (dominio,codice,descrizione,ordine) values ('PCO','P25','Other affected part of the body/Altra parte del corpo interessata',25);



DELETE FROM parametri WHERE DOMINIO ='EUR' OR (DOMINIO ='DOM' AND CODICE='EUR');
insert into parametri (dominio,codice,descrizione) values ('DOM','EUR','Costi stimati in Euro');
insert into parametri (dominio,codice,descrizione,ordine) values ('EUR','E01','below/sotto 1000 EURO',1);
insert into parametri (dominio,codice,descrizione,ordine) values ('EUR','E02','between/tra 1 001 and/e 5 000 EURO',2);
insert into parametri (dominio,codice,descrizione,ordine) values ('EUR','E03','between/tra 5001 and/e 10 000 EURO',3);
insert into parametri (dominio,codice,descrizione,ordine) values ('EUR','E04','between/tra 10 001 and/e 20 000 EURO',4);
insert into parametri (dominio,codice,descrizione,ordine) values ('EUR','E05','between/tra 20 001 and/e 30 000 EURO',5);
insert into parametri (dominio,codice,descrizione,ordine) values ('EUR','E06','between/tra 30 001 and/e 200 000 EURO',6);
insert into parametri (dominio,codice,descrizione,ordine) values ('EUR','E07','above/oltre 200 000 EURO',7);

DELETE FROM parametri WHERE DOMINIO ='INL' OR (DOMINIO ='DOM' AND CODICE='INL');
insert into parametri (dominio,codice,descrizione) values ('DOM','INL','Livello Incidente');
insert into parametri (dominio,codice,descrizione) values ('INL','L01','Level/Livello 1');
insert into parametri (dominio,codice,descrizione) values ('INL','L02','Level/Livello 2');
insert into parametri (dominio,codice,descrizione) values ('INL','L03','Level/Livello 3');




DELETE FROM parametri WHERE DOMINIO ='CLI' OR (DOMINIO ='DOM' AND CODICE='CLI');
insert into parametri (dominio,codice,descrizione) values ('DOM','CLI','Clienti');
insert into parametri (dominio,codice,descrizione) values ('CLI','C01',' Not applicable/Non applicabile');
insert into parametri (dominio,codice,descrizione) values ('CLI','C02','AMD');
insert into parametri (dominio,codice,descrizione) values ('CLI','C03','Arcelor');
insert into parametri (dominio,codice,descrizione) values ('CLI','C04','BASF');
insert into parametri (dominio,codice,descrizione) values ('CLI','C05','Bayer');
insert into parametri (dominio,codice,descrizione) values ('CLI','C06','BP');
insert into parametri (dominio,codice,descrizione) values ('CLI','C07','Chevron Texaco');
insert into parametri (dominio,codice,descrizione) values ('CLI','C08','Corning');
insert into parametri (dominio,codice,descrizione) values ('CLI','C09','Dow');
insert into parametri (dominio,codice,descrizione) values ('CLI','C10','DuPont');
insert into parametri (dominio,codice,descrizione) values ('CLI','C11','Exxon Mobil');
insert into parametri (dominio,codice,descrizione) values ('CLI','C12','Hitachi');
insert into parametri (dominio,codice,descrizione) values ('CLI','C13','Hyundai');
insert into parametri (dominio,codice,descrizione) values ('CLI','C14','IBM');
insert into parametri (dominio,codice,descrizione) values ('CLI','C15','IDT');
insert into parametri (dominio,codice,descrizione) values ('CLI','C16','Infineon');
insert into parametri (dominio,codice,descrizione) values ('CLI','C17','Lyondell ');
insert into parametri (dominio,codice,descrizione) values ('CLI','C18','Micron');
insert into parametri (dominio,codice,descrizione) values ('CLI','C19','NEC');
insert into parametri (dominio,codice,descrizione) values ('CLI','C20','Philips');
insert into parametri (dominio,codice,descrizione) values ('CLI','C21','Shell');
insert into parametri (dominio,codice,descrizione) values ('CLI','C22','Siemens');
insert into parametri (dominio,codice,descrizione) values ('CLI','C23','Sony');
insert into parametri (dominio,codice,descrizione) values ('CLI','C24','ST');
insert into parametri (dominio,codice,descrizione) values ('CLI','C25','TI');
insert into parametri (dominio,codice,descrizione) values ('CLI','C26','Toshiba');
insert into parametri (dominio,codice,descrizione) values ('CLI','C27','Total');
insert into parametri (dominio,codice,descrizione) values ('CLI','C28','TSMC');
insert into parametri (dominio,codice,descrizione) values ('CLI','C29','Valero');


